### PR TITLE
chore: convert to Typescript (core code only, no tests)

### PR DESCRIPTION
**Pull request by kyegupov**
- [ ] Ready for review
- [ ] Follows CONTRIBUTING rules
- [ ] Reviewed by Snyk internal team

### CODE REVIEW

**Comment by lili2311** [comment]
Will review asap, have you tested this with the CLI & pip-deps already manually?

**Comment by kyegupov** [comment]
@lili2311 yes, tested locally, it works

**Comment by kyegupov** [comment]
verified with pip-deps as well, works normally

**Comment by lili2311** [comment]
Great! Please fill out the PR template approving

**Pull request merged**
