### PR TITLE
fix: handle path to local dir in requirements.txt

### PR DESCRIPTION
**Pull request by shaninja**
- [ ] Ready for review
- [ ] Follows CONTRIBUTING rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?

We encountered a case in which a `requirements.txt` file contained a line that is a path to a local directory. We could not parse it, and `snyk test` yielded an error.

We added a case to handle such local directory requirements - we extract the package's name from `setup.py`.

### CODE REVIEW

**Comment by kyegupov** [comment]
(restarted the Travis build)

**Comment by kyegupov** [comment]
can we have a test for this case?

**Comment by shaninja** [comment]
Thank you @kyegupov for fixing the tests!

I intended to add a test, but couldn't understand the existing test suite :/ will ask for some help from someone today.

**Comment by shaninja** [comment]
@kyegupov added a test, would appreciate another look 🙏

**Pull request merged**
